language: rust
env: FEATURES=""
matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env: FEATURES="i128"
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
